export const facilitiesToConsider = [
    "Schools",
    "Hospitals",
    "Churches",
    "Libraries",
    "Police Stations",
    "Fire Stations",
    "Government Offices",
    "Community Centers",
    "Shopping Malls",
    "Grocery Stores",
    "Restaurants",
    "Cafes",
    "Cinemas",
    "Gyms",
    "Parks",
    "Theaters",
    "Sports Centers",
    "Banks",
    "Post Offices",
    "Museums",
    "Art Galleries",
    "Hotels",
    "Apartments",
    "Houses",
    "Condominiums",
    "Office Buildings",
    "Warehouses",
    "Factories",
    "Workshops",
    "Stadiums",
    "Convention Centers",
    "Airports",
    "Train Stations",
    "Bus Stations",
    "Car Dealerships",
    "Gas Stations",
    "Parking Lots",
    "School Buildings",
    "University Buildings",
    "Hospital Buildings",
    "Church Buildings",
    "Library Buildings",
    "Police Station Buildings",
    "Fire Station Buildings",
    "Government Office Buildings",
    "Community Center Buildings",
    "Shopping Mall Buildings",
    "Grocery Store Buildings",
    "Restaurant Buildings",
    "Cafe Buildings",
    "Cinema Buildings",
    "Gym Buildings",
    "Park Buildings",
    "Theater Buildings",
    "Sports Center Buildings",
    "Bank Buildings",
    "Post Office Buildings",
    "Museum Buildings",
    "Art Gallery Buildings",
    "Hotel Buildings",
    "Apartment Buildings",
    "House Buildings",
    "Condominium Buildings",
    "Office Building Complexes",
    "Warehouse Buildings",
    "Factory Buildings",
    "Workshop Buildings",
    "Stadium Buildings",
    "Convention Center Buildings",
    "Airport Buildings",
    "Train Station Buildings",
    "Bus Station Buildings",
    "Car Dealership Buildings",
    "Gas Station Buildings",
    "Parking Lot Buildings",
    // Add more building types as needed
];

